name: Build and Deploy
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: npm install
      run: npm i

    - name: npm build
      run: npm run build

    - name: deploy
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
          cd docs/.vuepress/dist
          git config --global user.email "phhhhhj@gmail.com"
          git config --global user.name "hyunjung"
          git init
          git add -A
          git commit -m 'deploy with vuepress(action)'
          git push -f https://${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git main:gh-pages